# Project: 项目4
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = 比较数值大小/main.o
LINKOBJ  = 比较数值大小/main.o
LIBS     = -L"C:/Users/ASUS/Desktop/Dev-Cpp/MinGW64/lib" -L"C:/Users/ASUS/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/ASUS/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/ASUS/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/ASUS/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/ASUS/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/ASUS/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/ASUS/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/ASUS/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 连乘.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

比较数值大小/main.o: 比较数值大小/main.c
	$(CC) -c 比较数值大小/main.c -o 比较数值大小/main.o $(CFLAGS)
